version: "3.8"

services:
  zoekt-indexserver:
    build:
      context: ../../airflow-hub
      dockerfile: docker/Dockerfile.airflow
    container_name: zoekt-indexserver
    platform: "${DOCKER_DEFAULT_PLATFORM}"
    ports:
      - "${ZOEKT_UI_PORT}:6070"
    # IDX_CLAUDE_API_KEY will be injected as a Docker secret or environment variable
    # Caddy basic-auth credentials can be injected here if needed for reverse proxy
    volumes:
      - ${HOME}/repos:/repos
    restart: unless-stopped

  sourcebot:
    build:
      context: .
    container_name: sourcebot
    platform: "${DOCKER_DEFAULT_PLATFORM}"
    ports:
      - "${SOURCEBOT_UI_PORT}:3000"  # Sourcebot UI
    # IDX_CLAUDE_API_KEY will be injected as a Docker secret or environment variable
    # Caddy basic-auth credentials can be injected here if needed for reverse proxy
    
    volumes:
      - ${HOME}/repos:/repos
    restart: unless-stopped

  indexagent:
    build:
      context: ../../IndexAgent
    container_name: indexagent
    platform: "${DOCKER_DEFAULT_PLATFORM}"
    ports:
      - "${INDEXAGENT_API_PORT}:8080"  # Expose the IndexAgent API
    environment:
      - CONFIG_PATH=/path/to/config.yaml
      - CLAUDE_MODEL=${CLAUDE_MODEL:-claude-3-opus-2025-05-02}
    volumes:
      - ${HOME}/repos:/repos
      - ../reports:/app/reports
      - ./docs/auto:/app/docs/auto
    restart: unless-stopped
    secrets:
      - claude_api_key

secrets:
  claude_api_key:
    file: /Users/preston/.secrets/claude_api_key.secret

volumes:
  baseline_logs:
